language: ruby
sudo: false
cache: bundler

rvm:
  - 1.9.3
  - 2.2.6

gemfile:
  - gemfiles/active_record_3.1.gemfile
  - gemfiles/active_record_3.2.gemfile
  - gemfiles/active_record_4.0.gemfile

matrix:
  include:
    - gemfile: gemfiles/active_record_3.1.gemfile
      rvm: 1.9.3
    - gemfile: gemfiles/active_record_3.2.gemfile
      rvm: 2.2.6
    - gemfile: gemfiles/active_record_4.0.gemfile
      rvm: 2.2.6
